### ISSUE TITLE
Monitoring tab is absent in initial UI for AdminServer

### ISSUE THREAD

**Issue by andrejusc** [oracle/weblogic-remote-console#11]
Use case:
WLS: 14.1.1.0.0
JDK: 11
Default quickstart wl_server domain with AdminServer in it
Browser remote console from this repo: v2.3.0

While connected to that AdminServer via Browser console - could see such list of tabs for it under `Servers/AdminServer` tree node:
```
General
Protocols
Cluster
Migration
Web Services
Health
Logging
Debug
SAML
Advanced
Referenced By
```

but don't see important `Monitoring` tab (default URL would be: https://localhost:7002/console/console.portal?_nfpb=true&_pageLabel=ServerMonitoringTabgeneralTabPage&handle=com.bea.console.handles.JMXHandle%28%22com.bea%3AName%3DAdminServer%2CType%3DServer%22%29 ) available in regular WLS Admin console, where one could see JDK version and OS presented.
Is that hidden on purpose currently or still in some TODO activity?

**Comment by lfeigen** [comment]
Sorry for missing this issue for so long.

Monitoring is a whole separate perspective ("Monitoring Tree") in the WebLogic Remote Console.  It can be accessed by clicking the third icon in the left column (the picture of a gauge) or by going "Home" and clicking on "Monitoring Tree".
